kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.32.5
  extraPortMappings:
  - containerPort: 32080
    hostPort: 32080
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.5