kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.32.5
  extraPortMappings:
  - containerPort: 32000
    hostPort: 32000
    protocol: TCP
  - containerPort: 32080
    hostPort: 32080
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.5
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.138.154:5000"]
    endpoint = ["http://192.168.138.154:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.138.154:5000".tls]
    insecure_skip_verify = true