# Default values for java-maven-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Application Configuration
app:
  name: "java-maven-app"
  version: "1.0"

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 192.168.138.154:5000/repository/docker-hosted/java-maven-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"

namespace: "apps"

# Deployment Configuration
deployment:
  name: "java-maven-app-deployment"
  replicaCount: 1

  # Container resources
  resources:
    requests:
      memory: "10Mi"
      cpu: "10m"
    limits:
      memory: "100Mi"
      cpu: "100m"

  # Container port
  containerPort: 8080

# Service Configuration
service:
  name: "java-maven-app-service"
  type: "NodePort"
  port: 80
  targetPort: 8080
  nodePort: 32000

# Docker Registry Secret Configuration
dockerRegistry:
  # Registry server URL
  server: "192.168.138.154:5000"
  
  # Secret name (same as your current secret)
  secretName: "regcred"

  # These will be populated by Jenkins pipeline
  username: ""
  password: ""