controller:
  image: "jenkins/jenkins"
  tag: "2.514-jdk21"
  imagePullPolicy: "Always"
  
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  serviceType: NodePort
  servicePort: 8080
  targetPort: 8080
  nodePort: 32080

  serviceAccount:
    create: true
    name: "jenkins"

  adminUser: "admin"
  adminPassword: "admin"
  
  # List of plugins to be install during Jenkins controller start
  installPlugins:
    - kubernetes:4353.vb_47977da_9417 
    - workflow-aggregator:608.v67378e9d3db_1 
    - git:5.7.0
    - configuration-as-code:1971.vf9280461ea_89
    - dark-theme:567.v9d3ca_a_3142f5