namespaceOverride: "jenkins"

controller:
  tag: "2.514-jdk21"

  adminUser: "admin"
  adminPassword: "admin"

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  
  nodePort: 32080
  serviceType: NodePort

  installPlugins:
    - kubernetes:4353.vb_47977da_9417 
    - workflow-aggregator:608.v67378e9d3db_1
    - workflow-multibranch:806.vb_b_688f609ee9
    - git:5.7.0
    - configuration-as-code:1971.vf9280461ea_89
    - dark-theme:567.v9d3ca_a_3142f5
    - ws-cleanup:0.48
    - job-dsl:1.93

  additionalSecrets:
    - name: nexus-jenkins-username
      value: admin
    - name: nexus-jenkins-password
      value: admin

  JCasC:
    defaultConfig: true
    configUrls: []
    # - https://acme.org/jenkins.yaml
    # Remote URL:s for configuration files.
    configScripts:
      welcome-message: |
       jenkins:
         systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "nexus-jenkins"
                      username: "${nexus-jenkins-username}"
                      password: "${nexus-jenkins-password}"
                      description: "Nexus credentials for Jenkins"
      seed-job: |
        jobs:
          - script: |
              freeStyleJob('seed-job-loader') {
                displayName('Job Definitions Loader')
                description('Automatically loads job definitions from Github')

                scm {
                  git {
                    remote {
                      url('https://github.com/apostoliseq/kind-cluster.git')
                      credentials('')
                    }
                    branch('main')
                  }
                }

                triggers {
                  scm('H/5 * * * *')
                }

                steps {
                  dsl {
                    external('helm-charts/jenkins/jobs/**/*.groovy')
                    removeAction('DELETE')
                    removeViewAction('DELETE')
                    ignoreExisting(false)
                  }
                }
              }
      # global-libraries: |
      #   unclassified:
      #     globalLibraries:
      #       libraries:
      #         - name: "shared-library"
      #           defaultVersion: "main"
      #           implicit: false
      #           allowVersionOverride: true
      #           includeInChangesets: false
      #           retriever:
      #             modernSCM:
      #               scm:
      #                 git:
      #                   remote: "https://github.com/apostoliseq/jenkins-shared-library.git"
      #                   credentialsId: ""

serviceAccount:
  create: true
  # The name of the service account is autogenerated by default
  name: "jenkins"
  annotations: {}
  extraLabels: {}
  imagePullSecretName: