apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app-deployment
  namespace: apps
  labels:
    app: java-maven-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app-pod
  template:
    metadata:
      labels:
        app: java-maven-app-pod
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: java-maven-app
          image: 192.168.138.154:5000/repository/docker-hosted/java-maven-app:1.0
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"