apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-service
  namespace: apps
spec:
  selector:
    app: java-maven-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort